### PR TITLE
PC2/PC58 Handle error messages while registration

### PR DESCRIPTION
**Pull request by MuscularSloth**
-Prevent close registration window if error
-Prevent disabling form submit if error
-Add submit on enter in any field
-Exclude showpswd buttons from focus
-Clear error on fields change

### CODE REVIEW

**Review by KenAdams777 — APPROVED** [review]
All is good. Good job!

**Review by KenAdams777 — COMMENTED** [review]
Hm... didn't actually find out how do you prevent the successful registration of a user with an email that had been registered earlier? Before it was possible to register the same user twice without any warnings or errors. Don't see in the code where do you implement any error notification?

**Review by KenAdams777 — COMMENTED** [review]
I was trying to cancel approval but it didn't work out, so there are two redundant comments here.

**Review by bejalane — APPROVED** [review]

**Comment by MuscularSloth** [comment]
> Hm... didn't actually find out how do you prevent the successful registration of a user with an email that had been registered earlier? Before it was possible to register the same user twice without any warnings or errors. Don't see in the code where do you implement any error notification?

This logic has been already implemented by Max or you. Look at the row 305. I only fixed what was broken and did some improves.

**Review by KenAdams777 — APPROVED** [review]

**Pull request merged**
